# Generated by Django 3.2.8 on 2021-10-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='creationDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
